# NumPy

NumPy es una biblioteca de cálculo numérico para Python que da soporte para vectores y matrices, funciones para algebra lineal, generación de valores aleatorios, aplicación de transformadas de Fourier, polinomios, estadística y funciones matemáticas. Las funciones matemáticas disponibles en Numpy se diferencian de las disponibles en el módulo `math` de Python en el soporte a los arreglos de Numpy (como vectores y matrices).

Si usas Anaconda este paquete ya viene instalado por defecto pero si se usa miniconda o pip debe instalarse.

````python
conda install numpy # Usando el gestor conda de Anaconda/Miniconda
pip install numpy # Usando el gestor pip (puede requerir instalar más paquetes)
````

Para comenzar a usarlo debemos importar el módulo.

In [1]:
import numpy as np # Se importa y se asocia el alias `np`.

## Arreglos

El elemento fundamental en Numpy son los arreglos (`ndarray` o `array`) que son de alguna forma un equivalente a las matrices. Los arreglos pueden tener una o más dimensiones (también llamados ejes), permitiendo distinguir de forma natural los vectores cuando se posee un solo eje.

In [2]:
A = np.array([[0, 5, 1], [7, 2, 6], [4, 8, 2]]) # Listas dentro de listas son filas de la matriz
b = np.array([1, 7, 6]) # Una lista genera un vector

In [3]:
print(A.ndim) # Número de ejes: 2
print(b.ndim) # Número de ejes: 1
print(A.shape) # Dimensión o forma: (3, 3)
print(b.shape) # Dimension o forma: (3,)
print(A.size) # Total de elementos: 9
print(b.size) # Total de elementos: 3

2
1
(3, 3)
(3,)
9
3


La información de la dimensión y del acceso a los elementos (indexación) usa la información en orden del eje 0 en adelante. El eje 0 es el dado por el conjunto de elementos más externo. En un vector, al solo tener un eje, su único índice corresponde al orden de los elementos en el vector. En una matriz, el primer índice equivale al orden de las listas las cuales definen las filas y el segundo índice es el orden de elementos en dichas listas (equivalente a la columna).

In [4]:
print(A[0, 1]) # Imprime el elemento de la fila 0 y columna 1: 5
print(b[0]) # Imprime el elemento 0 del vector: 1
print(A[:, 1]) # `:` representa todos. Muestra la columna 1. También se usa para rangos.
print(A[:2, 0]) # Extrae un vector dado por la columna 0 y las filas 0 y 1.
print(A[0:2, 1:]) # Submatriz

5
1
[5 2 8]
[0 7]
[[5 1]
 [2 6]]


## Arreglos especiales

Numpy define algunos arreglos especiales para su rápida creación, que de otra forma impricarían múltiples líneas para su inicialización. Algunos son:

In [5]:
print(np.ones(2)) # Vector de unos de 2 elementos
print(np.zeros([2, 3])) # Matriz rectangular de ceros de 2 filas y 3 columnas
print(np.eye(3)) # Matriz identidad de 3x3
print(np.arange(2, 5, 0.5)) # Equivalente a `range` para flotantes
print(np.linspace(1, 3, 11)) # Intervalo cerrado de 11 datos entre 1 y 3.
print(np.random.random([3, 2])) # Matriz aleatoria de 3x2

[1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[2.  2.5 3.  3.5 4.  4.5]
[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3. ]
[[0.67316691 0.4162536 ]
 [0.4386637  0.19058099]
 [0.04524685 0.29770852]]


## Álgebra lineal con Numpy

Los arreglos en Numpy no son directamente vectores ni matrices en el sentido matemático, por lo cual los operadores aritméticos entre los arreglos no operan como en el álgebra lineal. En su lugar, las operaciones se hacen elemento a elemento, lo que coincide con la suma y resta de matrices.

In [6]:
I2 = np.eye(2)
L2 = np.linspace(1, 7, 4).reshape(2, 2)
print(I2)
print(R2) 

[[1. 0.]
 [0. 1.]]


NameError: name 'R2' is not defined

In [ ]:
print(I2 + L2) # Suma de arreglos/matrices
print(I2 - L2) # Resta de arreglos/matrices

Para el producto matricial es necesario usar la función `dot`. En el caso de la potencia se requiere la función especifica del módulo `linalg`.

In [ ]:
print(I2 * L2) # Producto elemento a elemento
print(np.dot(I2, L2)) # Producto matricial
print(L2**2) # Potencia elemento a elemento
print(np.linalg.matrix_power(L2, 2)) # Potencia matricial

Se pueden obtener propiedades matriciales como la transpuesta y la diagonal de la matriz a partir de métodos del arreglo, y algunas operaciones como la inversa, el determinante, autovalores y norma con funciones de Numpy.

In [ ]:
print(L2.T) # Transpuesta de la matriz
print(L2.diagonal()) # Diagonal de la matriz
print(np.linalg.inv(L2)) # Matriz inversa
print(np.linalg.det(L2)) # Determinante de la matriz
print(np.linalg.eig(L2)) # Autovalores y autovectores
print(np.linalg.norm(b)) # Norma vectorial o matricial

También es posible solucionar sistemas matriciales $Ax=b$.

In [ ]:
# A y b definidos al inicio de la sección
np.linalg.solve(A, b) # Solución del sistema Ax=b

## Funciones sobre arreglos

Numpy define funciones universales para usar sobre arreglos, que funcionan como los operadores por defecto, elemento a elemento. Esto facilita la aplicación de funciones matemáticas de manera rápida sobre conjuntos de datos.

In [ ]:
PI = np.pi
angulos = np.array([0, PI/4, PI/3, PI/2, PI])
print(np.sin(angulos))
print(np.cos(angulos))
print(np.exp(angulos))

## Estadística

Numpy contiene funciones que permiten realizar estadísticas de los datos de arreglos.

In [ ]:
muestra = np.random.random(15)*10 # Datos
print(muestra)

In [ ]:
print(muestra.min()) # Muestra el menor elemento
print(muestra.max()) # Muestra el máximo elemento
print(muestra.mean()) # Muestra la media de los elementos
print(np.median(muestra)) # Muestra la mediana de los elementos
print(muestra.std()) # Desviación estándar

## Actividad

Dado el sistema de ecuaciones lineales,

\begin{eqnarray}
2x + y & = & 5\\
-x + y & = & 2
\end{eqnarray}

1.  Forme el sistema matricial $Ax=b$ equivalente.  
1.  Cree los arreglos Numpy correspondientes a la matriz $A$ y el vector $b$.  
1.  Calcule con Numpy el determinante y autovalores (sin autovectores) de $A$.  
1.  Encuentre la solución para $x$ con ayuda de Numpy.  
1.  Calcula la norma euclideana con Numpy del vector solución $x$.  
1.  Calcule el logaritmo natural sobre el vector solución $x$ con funciones universales de Numpy.  

## Recursos adicionales

Para complementar el aprendizaje de Numpy y su instalación, se recomiendas las siguientes fuentes:

+   [Numpy User Guide](https://docs.scipy.org/doc/numpy/user/).  
+   [MATLAB to Python: A migration guide](https://www.enthought.com/wp-content/uploads/Enthought-MATLAB-to-Python-White-Paper.pdf).  